name: Lint Code
on:
  push:
    branches: [ master ]
  pull_requests:
    branches: [ master ]

jobs:
  builds:
    runs-on: ubuntu-latest

      steps:

      -name: Checkout Code
       uses: actions/checkout@v2
       with:
         fetch-depth: 0

      -name: Lint Code
       uses: github/super-linter@v4
       env:
         VALIDATE_ALL_CODEBASE: true
         VALIDATE_BASH: true
         VALIDATE_YAML: true
         GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
